# Generated by Django 4.1.6 on 2023-03-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fooditems',
            new_name='fooditem',
        ),
    ]
