# Generated by Django 4.1.6 on 2023-03-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='foodTitle',
            new_name='food_title',
        ),
    ]
